### ISSUE TITLE
Shared module does not work

### ISSUE THREAD

**Issue by sisisin** [typeless-js/typeless#10]
### details

When the same `typeless module` is used by multiple `React Component`, in the following procedure `$unmonting ($unmounted)` dispatched after `$mount`.
At this time, `reducer` and `epic` will be unregistered.

1. Use `typeless module` (created by typeless's `createModule` API) in a `React Component`
2. Unmount the component and mount other `React Component` which uses the same `typeless module` (unmount and mount must be triggered at the same rendering step)
3. Then, `$unmounting` and `$unmounted` are dispatched after `$mounted` action.

### reproduction

- checkout [this repo](https://github.com/sisisin-sandbox/typeless-mount-behavior)
- start app and open `http://localhost:3000`
- click `toggle state`
- click `show foo`

Then, `Foo/SHOW_FOO` action is dispatched, but epic won't be executed.

### expected behavior

In this case, run `FooAction.showFoo` epic normaly.

### environment

typeless: `0.1.9-alpha.0` , `0.2.0`
react: `^16.8.4`

**Comment by BetterCallSky** [comment]
> 3. Then, `$unmounting` and `$unmounted` are dispatched after `$mounted` action.

This can be hard to fix.
The module is loaded in `React.memo` because it's must be available immediately.
For example:
```ts
useModule()
const myState = useMappedState(...)
```
If I change it to `React.useEffect`, then you won't be able to use `useMappedState` because module is not loaded yet.

Unmounting occurs in `React.useEffect(() => () => {...});`, and it seems that React invokes the deregister callback from `useEffect` after invoking the contructor from another component.

See example https://codesandbox.io/s/reverent-smoke-iei6y
console log is:
- memo B
- unload A
- load B

**Comment by sisisin** [comment]
@BetterCallSky Thanks for replying.
In my mind, to change `Store` class to following code, this problem is fixed.
https://github.com/sisisin/typeless/compare/beta...sisisin:fix/shared-module-mounting

This change has a problem in some case.
In follwoing example, when `Component` is unmounted, this will not be disabled `ModA`'s `Store`.

```tsx
const ModA = () => handle();
const Component = () => <>
  <ModA />
  <ModA />
</>
```

But, I think this behavior is better than now.
What do you think this?

**Comment by BetterCallSky** [comment]
@sisisin looks good!

**Comment by BetterCallSky** [comment]
Can you check https://codesandbox.io/s/xp7fh?
I did some changes because 'socket-hmr' example wasn't working properly.
There a new lifecycle action `$init`. I hope I will finish the beta version soon and release it with updated docs.

**Comment by sisisin** [comment]
Thank you for your change!
I think resolved this issue.
