### ISSUE TITLE
Automatically deployed when a pull request is created / updated

### ISSUE THREAD

**Issue by sisisin** [typeless-js/typeless#50]
I think automatically deployment should run only when master branch is updated.
But now, deployment runs when a pull request is created/updated.

**Comment by BetterCallSky** [comment]
Are there any issues? On every PR, Netlify creates a new preview for the documentation page.

**Comment by sisisin** [comment]
When pull request is updated, it seems that it is deployed to production env, too (unless my misunderstand...).
I think this is a problem.

**Comment by BetterCallSky** [comment]
Production shouldn't be updated.

https://github.com/typeless-js/typeless/pull/48
Before I merged it, I checked the https://typeless.js.org and links were broken, but it was fixed on the preview website. This is correct.

Do you have any examples? I will keep this issue open to monitor it, but the build is handled by the netlify plugin.

**Comment by sisisin** [comment]
Sorry, this is my misunderstand.
I pushed and create Pull request #54 ,but production is not deployed.
