### ISSUE TITLE
Add type testing

### ISSUE THREAD

**Issue by sisisin** [typeless-js/typeless#57]
### Motivation

`typeless` has complex type inference, but has no test for types.
This causes that to fix and verify types is difficulty (e.g. #30).

So, I think `typeless` need to add type testing.

### Proposal

https://github.com/sisisin/typeless/pull/2/commits/da771a77e03790a563740247d0e8d4a8c9845cf2

#### Pros

This approach is very simple and no dependency.
Testing type is done all of `tsc`

#### Cons

Need to make all of assert functions and test structure helpers.
Developer maybe to have pain if more complex testing.

#### Other plan

Using [tsd](https://github.com/SamVerschueren/tsd)

**Comment by sisisin** [comment]
@lstkz How about this idea?

**Comment by lstkz** [comment]
Sure, I am fine with that.
Does it catch the issue with if there is an `any` type?

For example:

```
withPayload: () => ({ payload: { x: 'string' } }),
```

It has a type `() => {payload: {x: string}}`. What if there is a bug, and it has a type `() => any`? Will tests catch that?

**Comment by sisisin** [comment]
Yeah, it'll be catched.

[playground](https://www.typescriptlang.org/play/#code/KYDwDg9gTgLgBDAnmYcAqzgFECOAeAQQBo4AhAPjgF44AKPNc2gSmsrTlBmADsATAM5wCcAPxwAjHABccAEysuvQXDwAoOOjVNWVdpxDd+Q0mMkz5GszCgBXYFdkAzAIYAbAcADcataEiwcE62PADGMACWEDxwLgKesBgoeAD6HErGCHbAOnAA3gC+vkgocADC0FDA4QDqETAAFgAKLohuEC581HS6lHlwYK3tnbL9ILICNhE8AOZwBfNqJagAkmGV1TB1jS1tHV00LGyxPIi+cQkwScAMmLh4FVBVtfXNQ-ska6EbLzvvneQdGoLsBEphbih7o9nltXrthnwSNDNts3nsAUCgA)

**Comment by sisisin** [comment]
I'm going to get on with this issue when #60 merged.

**Comment by lstkz** [comment]
https://github.com/microsoft/TypeScript/wiki/Roadmap#39-may-2020

Do you think we can use `// @ts-expect-error Comments` instead? A new feature in 3.9.

**Comment by sisisin** [comment]
I think `@ts-expect-error` is not for this case.
When `@ts-expect-error` is written in code, it suppresses all errors that originate on the following line.
See following example.

```typescript
describe('Epic#toStream', ()=>{
  it('should be thrown error when invalid Action', ()=>{
    const epic = new Epic()
    const invalidAction = {}

    // Calling `toStream` with invalidAction should cause compile error, but it is suppressed by @ts-expect-error comment.
    // @ts-expect-error
    const stream = epic.toStream(invalidAction, deps);

    // and some assertion...
  })
})
```

Solving our issue that `typeless` lacks testing for complex type is not expect error but assert that type is correct
So, I think `@ts-expect-error` is not for this case.

**Comment by sisisin** [comment]
@lstkz I think `@ts-expect-error` is not for this case.
When `@ts-expect-error` is written in code, it suppresses all errors that originate on the following line.
See following example.

```typescript
describe('Epic#toStream', ()=>{
  it('should be thrown error when invalid Action', ()=>{
    const epic = new Epic()
    const invalidAction = {}

    // Calling `toStream` with invalidAction should cause compile error, but it is suppressed by @ts-expect-error comment.
    // @ts-expect-error
    const stream = epic.toStream(invalidAction, deps);

    // and some assertion...
  })
})
```

Solving our issue that `typeless` lacks testing for complex type is not expect error but assert that type is correct
So, I think `@ts-expect-error` is not for this case.

**Comment by lstkz** [comment]
Ok, I see.
You can submit a PR.
