### ISSUE TITLE
An error occurs in the example "Counter".

### ISSUE THREAD

**Issue by Natsuume** [typeless-js/typeless#62]
The tsconfig.json in the "Counter" example have an error.
https://typeless.js.org/introduction/examples

I accessed "Live demo" link, but "Browser" tab does not display correct content.
https://codesandbox.io/s/h84n1

> Error
We weren't able to parse: '/tsconfig.json': Parse error on line 4:
...aultImports": true, // no errors on comm
-----------------------^
Expecting 'STRING', got 'undefined'

**Comment by lstkz** [comment]
@Natsuume thanks for catching that. Fixed.
