### ISSUE TITLE
useMappedState should prevent re-render when result got same value

### ISSUE THREAD

**Issue by sisisin** [typeless-js/typeless#64]
`useMappedState` execute force re-render when `Store`'s subscription emitted.
https://github.com/typeless-js/typeless/blob/fbb6de9d78b0afe09cf247d225c5cce42b2c53fd/packages/typeless/src/useMappedState.ts#L69

When a Component depends on typeless module's state, performance tuning more difficulty by this behavior.

### Expected behavior

It shouldn't execute force re-render when `useMappedState`'s result got same value.

### Prior art

react-redux's `useSelector` and reselect's `createSelector` are solved this problem.
Following example, I made comparison of typeless and react-redux/reselect.
[code sandbox](https://codesandbox.io/s/practical-meadow-hwjrn)

---

@lstkz I'll make PR if you don't mind.

**Comment by lstkz** [comment]
Can you create an example?
The function inside `useMappedState` is executed every store change.
if the result is the same, then the component won't re-render. I believe there should be tests for that https://github.com/typeless-js/typeless/blob/master/packages/typeless/__tests__/integration.test.tsx.

**Comment by sisisin** [comment]
Here is example
https://codesandbox.io/s/practical-meadow-hwjrn

`Counter` Component only depends on  `counter1`, so it shouldn't be re-render when update `counter2`.

[FYI] In this branch, I fixed this and wrote test case
https://github.com/sisisin/typeless/commit/d8e1a142a55905d3fcb3f11849ddd015565e6cf7

**Comment by lstkz** [comment]
Sorry for the late reply. Yes, it's a bug. Can you submit a PR?
awesome thanks!
