### ISSUE TITLE
`0.1.9-alpha.0` version should publish with beta tag.

### ISSUE THREAD

**Issue by sisisin** [typeless-js/typeless#9]
Now, typeless `0.1.9-alpha.0` version published as latest at npm.
So, run `npm install typeless`, then installed `0.1.9-alhpa-0` version.

`0.1.9-alpha.0` is developing now, and different from [document](https://typeless.js.org/introduction/quick-start)
This causes counfusing for users, so I think to publish with beta tag.

**Comment by BetterCallSky** [comment]
@sisisin thanks for catching it.
A default npm version should be fixed now.
